# Changes made from the base config, make sure to read the docs provided in the third comment to modify according to one's liking
# This is solely meant for GlazeWM users as I haven't touched Komorebi for I love GlazeWM's simplicity.
# UPDATE: Done modifying with Komorebi!
# For more information about configuration options, please visit the Wiki https://github.com/amnweb/yasb/wiki
watch_stylesheet: true
watch_config: true
debug: false
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: false
      duration: 1000
    blur_effect:
      enabled: false
      acrylic: True
      dark_mode: True
      round_corners: True
      round_corners_type: "normal"
      border_color: "System"
    window_flags:
      always_on_top: true
      windows_app_bar: true # This interferes with apps in full-screen. Notably while watching videos in full screen
    dimensions:
      width: "100%"
      height: 30
    padding:
      top: 0
      left: 0
      bottom: -1
      right: 0
    widgets:
      left: ["notes"]
      center: ["clock"]
      right:
        [
          "disk",
          "volume",
          "github",
          "notifications",
          "power_menu",
          "update",
        ]
widgets:
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 16
      animation:
        enabled: false
      title_label:
        enabled: false
        show: "always"
        min_length: 10
        max_length: 30
      ignore_apps:
        processes: []
        titles: []
        classes: []
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "Komorebi Offline"
      label_workspace_btn: ""
      label_workspace_active_btn: ""
      label_workspace_populated_btn: ""
      label_default_name: ""
      label_zero_index: false
      hide_empty_workspaces: true
      hide_if_offline: false
      animation: false
      container_padding:
        top: 0
        left: 12
        bottom: 0
        right: 12
      btn_shadow:
        enabled: true
        color: "black"
        radius: 6
        offset: [1, 1]
  komorebi_control:
    type: "komorebi.control.KomorebiControlWidget"
    options:
      label: "<span>\udb84\udc47</span>"
      icons:
        start: "\uead3"
        stop: "\uead7"
        reload: "\uead2"
      run_ahk: false
      run_whkd: true
      show_version: false
      komorebi_menu:
        blur: false
        round_corners: True
        round_corners_type: "normal"
        border_color: "System"
        alignment: "left"
        direction: "down"
        offset_top: 6
        offset_left: -32
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
  notes:
    type: "yasb.notes.NotesWidget"
    options:
      label: "<span>\udb82\udd0c</span> {count}"
      label_alt: "{count} notes"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      menu:
        blur: false
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 220
        max_title_size: 150
        show_date_time: true
      icons:
        note: "\udb82\udd0c"
        delete: "\ue20d"
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      label_shadow:
        enabled: true
        color: "black"
        radius: 6
        offset: [1, 1]
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\ue62a</span>"
      menu_list:
        - { title: "User Home", path: "~" }
        - { title: "Download", path: "D:\\Downloads" }
        - { title: "Documents", path: "C:\\Users\\amn\\Documents" }
        - { title: "Pictures", path: "C:\\Users\\amn\\Pictures" }
      system_menu: true
      power_menu: false
      blur: false
      round_corners: true
      round_corners_type: "normal"
      border_color: "System"
      offset_top: 6
      offset_left: 0
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      alignment: "left"
      direction: "down"
      menu_labels:
        shutdown: "Shutdown"
        restart: "Restart"
        logout: "Logout"
        lock: "Lock"
        sleep: "Sleep"
        system: "System Settings"
        about: "About This PC"
        task_manager: "Task Manager"
      label_shadow:
        enabled: true
        color: "black"
        radius: 6
        offset: [1, 1]
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span>"
      label_alt: "{count} notifications"
      hide_empty: true
      tooltip: true
      callbacks:
        on_left: "toggle_notification"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: true
        color: "black"
        radius: 6
        offset: [1, 1]
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_percent}%"
      label_alt: "<span>\uefc5</span> SWAP: {swap_mem_percent}%"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      memory_thresholds:
        low: 25
        medium: 50
        high: 90
      label_shadow:
        enabled: true
        color: "black"
        radius: 6
        offset: [1, 1]
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]:.0f}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"
      label_shadow:
        enabled: true
        color: "black"
        radius: 6
        offset: [1, 1]
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\udb83\ude09</span>"
      image_path: "C:\\Users\\User\\Downloads\\Media\\Images"
      change_automatically: false
      update_interval: 60
      gallery:
        enabled: true
        blur: false
        image_width: 296
        image_per_page: 6
        show_buttons: false
        orientation: "landscape"
        image_spacing: 10
        lazy_load: false
        lazy_load_delay: 0
        lazy_load_fadein: 0
        image_corner_radius: 20
        enable_cache: true
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
  disk:
    type: "yasb.disk.DiskWidget"
    options:
      label: "<span>\uf473</span>"
      # label_alt: "<span>\uf473</span>"
      label_alt: "{volume_label}:{space[used][percent]}"
      volume_label: "C"
      update_interval: 60
      group_label:
        volume_labels: ["C", "D", "E", "O"]
        show_label_name: true
        blur: false
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 120
      callbacks:
        on_left: "toggle_group"
        on_right: "exec \"C:\\Users\\User\\Downloads\\programs\\wiztree_4_18_portable\\WizTree64.exe\""
      label_shadow:
        enabled: true
        color: "black"
        radius: 6
        offset: [1, 1]
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\udb80\udf5e"
      label_expanded: "\udb80\udf5f"
      label_position: "right" # Can be "left" or "right"
      icon_size: 15 # Can be any integer between 8 and 64
      pin_click_modifier: "alt" # Can be "ctrl", "alt" or "shift"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: true
      hide_if_offline: true
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}"
      label_alt: "{title} - {artist}"
      max_field_size:
        label: 24
        label_alt: 24
      show_thumbnail: true
      controls_only: false
      controls_left: true
      hide_empty: true
      thumbnail_alpha: 255
      thumbnail_padding: 30
      thumbnail_corner_radius: 0
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
      label_shadow:
        enabled: true
        color: "black"
        radius: 6
        offset: [1, 1]
      container_shadow:
        enabled: true
        color: "black"
        radius: 6
        offset: [1, 1]
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\ue0c2</span>{%A %d %B %Y %H:%M}<span>\ue0c0</span>"
      label_alt: "<span>\ue0c2</span>{%A %d %B %Y %H:%M}<span>\ue0c0</span>"
      timezones: []
      calendar:
        blur: true
        round_corners: true
        offset_top: 10
        offset_left: 20
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: "3bf4cf9a7c3f40d6b31174128242807"
      update_interval: 600
      hide_decimal: true
      location: "Tuticorin"
      callbacks:
        on_left: "toggle_card"
      weather_card:
        blur: false
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        icon_size: 64
        offset_top: 6
        offset_left: 74
      label_shadow:
        enabled: true
        color: "black"
        radius: 6
        offset: [1, 1]
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span>"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
        on_left: "exec cmd.exe /c start ms-settings:network"
        on_right: "toggle_label"
      wifi_icons: [
          "\udb82\udd2e", # 0% strength icon
          "\udb82\udd1f", # 1-20% strength
          "\udb82\udd22", # 21-40% strength
          "\udb82\udd25", # 41-80% strength
          "\udb82\udd28", # 81-100% strength
        ]
      label_shadow:
        enabled: true
        color: "black"
        radius: 6
        offset: [1, 1]
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8" # Icon for muted
        - "\uf026" # Icon for 0-10% volume
        - "\uf027" # Icon for 11-30% volume
        - "\uf027" # Icon for 31-60% volume
        - "\uf028" # Icon for 61-100% volume
      audio_menu:
        blur: false
        round_corners: True
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 80
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "toggle_mute"
      label_shadow:
        enabled: true
        color: "black"
        radius: 6
        offset: [1, 1]
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span>{percent}%"
      label_alt: "time: {time_remaining}"
      charging_options:
        icon_format: "{charging_icon}"
      status_thresholds:
        critical: 10
        low: 25
        medium: 75
        high: 95
        full: 100
      label_shadow:
        enabled: true
        color: "black"
        radius: 6
        offset: [1, 1]
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 0
      button_row: 4
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        # hibernate: ["\uf28e ", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]
      label_shadow:
        enabled: true
        color: "black"
        radius: 6
        offset: [1, 1]
  github:
    type: "yasb.github.GithubWidget"
    options:
      label: "<span>\ueba1</span>"
      label_alt: "Notifications {data}" # {data} return number of unread notification
      token: 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 # GitHub Personal access tokens (classic) https://github.com/settings/tokens
      max_notification: 20 # Max number of notification displaying in menu max: 50
      notification_dot:
        enabled: True
        corner: "bottom_left" # Can be "top_left", "top_right", "bottom_left", "bottom_right"
        color: "red" # Can be hex color or string
        margin: [1, 1] # x and y margin for the dot
      only_unread: true # Show only unread or all notifications;
      max_field_size: 54 # Max characters in title before truncation.
      update_interval: 300 # Check for new notification in seconds
      menu:
        blur: True # Enable blur effect for the menu
        round_corners: True # Enable round corners for the menu (this option is not supported on Windows 10)
        round_corners_type: "normal" # Set the type of round corners for the menu (normal, small) (this option is not supported on Windows 10)
        border_color: "System" # Set the border color for the menu (this option is not supported on Windows 10)
        alignment: "right"
        direction: "down"
      label_shadow:
        enabled: True
        color: "black"
        radius: 3
        offset: [1, 1]
  ai_chat:
    type: "yasb.ai_chat.AiChatWidget"
    options:
      label: "<span>\uf086</span>"
      chat:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_left: 0
        offset_top: 6
      icons:
        send: "\uf1d8"
        stop: "\uf04d"
        clear: "\uf1f8"
        assistant: "\udb81\ude74"
      notification_dot:
        enabled: false
        corner: "top_right"
        color: "red"
        margin: [0, 2]
      callbacks:
        on_left: "toggle_chat"
      providers:
        - provider: "Ollama"
          api_endpoint: "http://localhost:11434/v1"
          credential: "ollama"
          models:
            - name: "gemma3:1b"
              label: "Gemma3"
        - provider: "OpenAI"
          api_endpoint: "https://api.openai.com/v1"
          credential: "dsfsfsfs65sd6f56sd5f6"
          models:
            - name: "gpt-3.5-turbo"
              label: "GPT3.5 Turbo"
            - name: "gpt-4"
              label: "GPT4"
              temperature: 0.3
              top_p: 0.95
              max_tokens: 4096
              instructions: "C:/Users/amnweb/Desktop/custom_gpt_chatmode.md"
  brightness:
    type: "yasb.brightness.BrightnessWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "Brightness {percent}%"
      tooltip: true
      hide_unsupported: true
      brightness_toggle_level: [0, 50, 100]
      auto_light: false
      auto_light_icon: "\udb80\udce1"
      auto_light_night_level: 35
      auto_light_night_start_time: "19:00"
      auto_light_night_end_time: "06:45"
      auto_light_day_level: 75
      brightness_icons: [
          "\udb80\udcde", # Icon for 0-25% brightness
          "\udb80\udcdd", # Icon for 26-50% brightness
          "\udb80\udcdf", # Icon for 51-75% brightness
          "\udb80\udce0", # Icon for 76-100% brightness
        ]
      brightness_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
      callbacks:
        on_left: "toggle_label"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]

  vscode:
    type: "yasb.vscode.VSCodeWidget"
    options:
      label: "<span>\udb82\ude1e</span>"
      label_alt: "<span>\udb82\ude1e</span> recents"
      menu_title: "<span style='font-weight:bold'>VScode</span> recents"
      max_field_size: 50
      folder_icon: "\uf114"
      file_icon: "\uf016"
      truncate_to_root_dir: false
      hide_folder_icon: false
      hide_file_icon: false
      max_number_of_folders: 30
      max_number_of_files: 30 # set to 0 if you only want folders
      modified_date_format: "Date modified: %Y-%m-%d %H:%M"
      cli_command: "vscodium" # or "codium" or "windsurf" or any other CLI command to open the workspace
      menu:
        blur: true
        round_corners: true
        round_corners_type: "small"
        alignment: "center"
        offset_top: 0

  update:
    type: "yasb.update_check.UpdateCheckWidget"
    options:
      winget_update:
        enabled: true
        label: "<span>\uf0ab</span>{count}"
        interval: 100
        exclude: []
      windows_update:
        enabled: false
        label: "<span>\uf0ab</span>{count}"
        interval: 240
        exclude: []
