watch_stylesheet: true
watch_config: true
debug: true
komorebi:
  start_command: 'sudo "C:\Program Files\AutoHotkey\v2\AutoHotkey64.exe" "D:\programs\komerobi\komorebi.ahk"'
  stop_command: "sudo komorebic.exe stop --bar"
  reload_command: "komorebic reload-configuration"
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false # Blur effect will be applied to the bar
      acrylic: false # Acrylic effect will be applied to the bar
      dark_mode: false # Dark mode will also add more shadow to the bar
      round_corners: True # Default radius from OS
      border_color: "#000000" # If is None border will be removed, System will use OS accent color, otherwise you can set your own HEX color (this option is related to round_corners=true)
    window_flags:
      always_on_top: true
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 30
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: [
          "traffic",
          "cpu",
          # "active_window"
        ]
      center: ["komorebi_workspaces"]
      right: [
          # "media",
          # "memory",
          # "weather",
          # "ip_info",
          "volume",
          "disk",
          "clock",
          "power_menu",
          "update",
        ]
widgets:
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}"
      label_alt: "{artist}"
      max_field_size:
        label: 30
        label_alt: 24
      show_thumbnail: false
      controls_only: false
      controls_left: true
      hide_empty: true
      thumbnail_alpha: 250
      thumbnail_padding: 0
      thumbnail_corner_radius: 0
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
  # memory:
  #   type: "yasb.memory.MemoryWidget"
  #   options:
  #     label: "<span>\uf4bc</span> {virtual_mem_outof}"
  #     label_alt: "<span>\uf4bc</span> {virtual_mem_outof}"
  #     update_interval: 10000
  #     callbacks:
  #       on_right: "exec cmd /c Taskmgr"
  # active_window:
  #   type: "yasb.active_window.ActiveWindowWidget"
  #   options:
  #     label: "{win[title]}"
  #     label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
  #     label_no_window: ""
  #     label_icon: true
  #     label_icon_size: 14
  #     max_length: 56
  #     max_length_ellipsis: "..."
  #     monitor_exclusive: true
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\udb80\udd50</span> {%A, %B %d, %Y - %H:%M}"
      label_alt: "<span>\udb80\udd50</span> {%A, %d %B %Y %H:%M}"
      timezones: []
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "Komorebi Offline"
      label_workspace_btn: "{index}"
      label_workspace_active_btn: "{index}"
      label_workspace_populated_btn: "{index}"
      label_default_name: "{index}"
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: false
      animation: true
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp_c}"
      label_alt: "{location}: Min {min_temp_c}, Max {max_temp_c}, Humidity {humidity}"
      api_key: "24b6c2cda6d84066b0304531241908"
      update_interval: 600 #Update interval in seconds, Min 600
      hide_decimal: true
      location: "USA Virginia" # You can use "USA Los Angeles 90006" {COUNTRY CITY ZIP_CODE}, or just city.
      callbacks:
        on_left: "toggle_label"
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\udb81\udd94"
        cloudyDay: "\uebaa"
        cloudyNight: "\uebaa"
        rainyDay: "\udb81\udd96"
        rainyNight: "\udb81\udd96"
        snowyIcyDay: "\udb81\udd92"
        snowyIcyNight: "\udb81\udd92"
        blizzard: "\udb81\udd93"
        default: "\uebaa"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8" # Icon for muted
        - "\uf026" # Icon for 0-10% volume
        - "\uf027" # Icon for 11-30% volume
        - "\uf027" # Icon for 31-60% volume
        - "\uf028" # Icon for 61-100% volume
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "<span color: #221f2e !important;padding-right: 6px;padding-left: 6px;'>\udb80\udf43 Â power menu</span>"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 0 # Millisecond
      button_row: 4
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        # hibernate: ["\uf28e ", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]

  update:
    type: "yasb.update_check.UpdateCheckWidget"
    options:
      winget_update:
        enabled: true
        label: "<span>\uf0ab</span>{count}"
        interval: 10
        exclude: []
      windows_update:
        enabled: false
        label: "<span>\uf0ab</span>{count}"
        interval: 240
        exclude: []

  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      # label: "<span>\udb82\udcfa</span> \uea9a{download_speed} \ueaa1{upload_speed}"
      label: "<span>\udb82\udcfa</span> Download {download_speed} | Upload {upload_speed}"
      label_alt: "<span>\udb82\udcfa</span> Download {download_speed} | Upload {upload_speed}"
      update_interval: 1000
      callbacks:
        # on_left: "toggle_label"
        on_right: "exec cmd /c Taskmgr"
  disk:
    type: "yasb.disk.DiskWidget"
    options:
      label: "<span class='a'>storage</span>"
      label_alt: "{volume_label} {space[used][gb]} / {space[total][gb]}"
      volume_label: "C"
      update_interval: 60
      group_label:
        enabled: true
        volume_labels: ["C", "D", "E", "F"]
        blur: true
        alignment: "center"
        direction: "down"
        distance: 6
      callbacks:
        on_right: "exec \"C:\\Users\\User\\Downloads\\programs\\wiztree_4_18_portable\\WizTree64.exe\""
  ip_info:
    type: "yasb.custom.CustomWidget"
    class_name: "ip_info"
    options:
      label: "<span class='as'>\udb81\udd9f</span>{data[ip]}"
      label_alt: "<span class='as'>\udb81\udd9f</span>{data[ip]}"
      class_name: "ip_info"
      exec_options:
        run_cmd: "curl.exe https://ipinfo.io"
        run_interval: 120000 # every 5 minutes
        return_format: "json"
        hide_empty: false
      callbacks:
        # on_left: "toggle_label"
        on_middle: "exec cmd /c ncpa.cpl" # open network settings
        on_right: "exec cmd /c start https://ipinfo.io/{data[ip]} " # open ipinfo in browser
  windows_workspaces:
    type: "yasb.windows_desktops.WorkspaceWidget"
    options:
      label_workspace_btn: "\udb81\udc3d"
      label_workspace_active_btn: "\udb81\udc3e"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"
      # label_shadow:
      #   enabled: true
      #   color: "black"
      #   radius: 3
      #   offset: [ 1, 1 ]
